# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NQz-u6LDNsMIyZUc5D4rpJpPAAJ2o6H
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('Employee.csv')
df.head()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_path = '/content/drive/My Drive/DataProjects/Employee.csv'  # Adjust if the filename differs
df = pd.read_csv(file_path)
df.head()

print(df.isnull().sum())

# Drop rows with missing values (if any)
df = df.dropna()

# Verify Data Types
print(df.dtypes)

print(df.columns)

print(df.columns.tolist())

df.groupby('Department')['Performance_Score'].mean()

df.sort_values(by='Performance_Score', ascending=False).head(5)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(df['Performance_Score'], kde=True)
plt.title('Employee Performance Score Distribution')
plt.show()